config/routes.rb
Portlandbikeswap::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  resources :index
  resources :categories do 
  	resources :components
  end
  resources :components
  root to: "index#index"
  resources :emailer
  #get "components/contact_form" => 'components#contact_form', :as => :contact_form
end

app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :component
end

app/models/brake.rb
class Brake < ActiveRecord::Base
  belongs_to :component
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :components
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  def self.search(query)
  	where("company ILIKE ? OR name ILIKE ?", "%#{query}%", "%#{query}%") 
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  belongs_to :component
end

app/models/index.rb
class Index < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :components
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #after_create :send_welcome_message
  def send_welcome_message
    UserMailer.signup_confirmation(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :email
	  #devise_parameter_sanitizer.for(:sign_in) << :email
	  devise_parameter_sanitizer.for(:sign_in) << :email
	end
  end

# before_filter :configure_permitted_parameters, if: :devise_controller?
#   protect_from_forgery with: :exception
#   protected
#   def configure_permitted_parameters
#     devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) }
    
#     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password ) }
#   end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
	@components = bike.all 
  end

  def new
	@bike = bike.new
  end

  def create
	@bike = bike.new(bike_params)
	if @bike.save
		redirect_to root_url, notice: "Your item has been added"
	else
		render "new"
	end
  end
    
  private
    def bike_params
      params.require(:bike).permit(:bike)
    end
end

app/controllers/brakes_controller.rb
class BrakesController < ApplicationController

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
	@categories = Category.all
  end

  def show
  	@category = Category.find(params[:id])
  end

end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  def index
  	
    @component = Component.find_by(params[:id])
    if params[:search]
      @components = Component.search(params[:search]).order("created_at DESC")
    else
      @components = Component.all.order('created_at DESC')
  end

  end

  def new
  	@component = Component.new
  end

  def show
    @component = Component.find(params[:id])
    
  end

  def create
  	@component = Component.new(component_params)
  	if @component.save
  		redirect_to root_url, notice: "Your item has been added"
  	else
  		render "new"
  	end
  end

  def destroy
    @component = Component.find(params[:id])
    @component.destroy
    redirect_to root_url
  end
  
  private
  def component_params
    params.require(:component).permit(:user_id, :category_id, :company, :name, :price, :condition, :description, :photo)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

	def index
		@components = Component.order('created_at DESC').limit(4).all
	end

end

app/controllers/users_controller.rb
class UsersController < ActiveRecord::Base
  def create
    @user = User.new(params[:user])
    if @user.save
      #UserMailer.signup_confirmation(@user).deliver
      redirect_to @user, notice: "Signed up successfully."
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h1>hello</h1>

<%= @category.name %>

<div class="jumbotron">Welcome to PDX Bike Swap</div>

app/views/categories/show.html.erb
 <% components = [] %>

<% Component.order('created_at DESC').all.each do |component| %>
  <% if component.category_id == @category.id  %>
    <% components << component %>
	<div class='container'>
	  <div class="thumbnail">
		<div class='row'>
		  <div class="col-sm-2">
			<%= image_tag component.photo(:thumb) %>
       	  </div>
		  <div class="col-sm-4">
		    <p>
			  <%= component.company %>: <%= component.name %><br>
			  price: $<%= component.price.to_i %><br>
			  condition: <%= component.condition %><br>
			</p>
		  </div>
		  <div class="col-sm-3">
		    Posted: <%= component.created_at.strftime("%b %d, %Y")%>
		  </div>
		  <div class="col-sm-3">
		    <%= link_to "More Info", component_path(component), :class=>'btn btn-success' %>
		  </div>
		</div>
	  </div>
    </div>
  <% end %>
<% end %>	

app/views/index/index.html.erb
<center>
  <div class="container">
  	<h1>Newest Listings</h1>
  </div>
</center>
<% @components.each do |component| %>

  <div class="col-sm-12 col-md-3">
    <div class="thumbnail">
      
        <%= image_tag component.photo(:medium) %>
   
      <div class="caption">
        <h3><center><%= component.company %>:<br> <%= component.name %></center></h3>
        <p>
          <center>price: $<%= component.price.to_i %></center>
          <center>condition: <%= component.condition %></center>
        </p>
        <p><center>
             <%= link_to "More Info", component_path(component), :class=>'btn btn-success' %></center></p>
      </div>
    </div>
  </div>
<% end %> <br><br><br><Br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portlandbikeswap</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'pdxbikeswap.png' %>
</head>
<body>
   <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <%= link_to "PDX Bike Swap", root_url, class: 'navbar-brand' %>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Home", root_url %></li>
      
      <li><%= link_to "Add Listing", new_component_path %></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown">Categories <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% Category.all.each do |category| %>
            <li><%= link_to category.part, category_path(category) %></li>
          <% end %>
        </ul>
      </li>
    </ul>  
    <%= form_tag(components_path, :class => 'nav navbar-nav navbar-left', :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Lisitings" %>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
    	<% if user_signed_in? %>
			 <li> Logged in as <strong><%= current_user.email %></strong>.</li>
			 <li> <%= link_to 'Edit profile', edit_user_registration_path %> </li>
			 <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
			<% else %>
			 <li> <%= link_to "Sign up", new_user_registration_path %> </li>
			 <li> <%= link_to "Login", new_user_session_path %> </li>
			<% end %>
			      
      <li>
    </ul>
  </div>
</div>
<div class="container">
  <%= bootstrap_flash %>

  <%= yield %>
  <span class="logo">
    <div class="align-left">
      
    </div>
  </span>
  <br><br>
</div>

</body>
</html>